### ISSUE TITLE
Counters 

### ISSUE THREAD

**Issue by stefanhusmann** [ds26gte/tex2page#2]
I sometimes define commands including counters in my my LaTeX preamble. Is it possible to make tex2page process these commands the same way LaTeX would do it and show the resulting numbers in HTML?

**Comment by ds26gte** [comment]
tex2page does recognize LaTeX's `\newcounter` -- including in the preamble -- so you must mean something else? Could you give a small example LaTeX file containing your desired feature so I can compare the PDF against the HTML?

Thanks.

**Comment by stefanhusmann** [comment]
Here it is. (github does not let me upload files ending in .tex here.)
[test.txt](https://github.com/ds26gte/tex2page/files/48994/test.txt)

**Comment by ds26gte** [comment]
Thanks. All the counter commands in your example file -- `\newcounter`, `\stepcounter`, `\setcounter`, `\addtocounter`, `\arabic` -- should work properly now. 

`\marginnote` is currently just a `span` with `class=marginnote`, so for now it just lies embedded in the text. You may want to redefine `\marginnote` appropriately for HTML so it stands out in other ways (e.g., enclosed in brackets or as a superscript), or devise a CSS definition for `.marginnote`, maybe with some `float` property. It will probably depend somewhat on the overall CSS for your document -- there may not be a general-purpose CSS solution that is pleasing on all browsers.

**Comment by stefanhusmann** [comment]
Thank you very much!
