### ISSUE TITLE
Making index.html fails

### ISSUE THREAD

**Issue by stefanhusmann** [ds26gte/tex2page#4]
On Arch Linux, using guile, the generated tex2page cannot compile index.tex to html:

;;; note: source file /home/haawda/paketierung/meine_Pakete/tex2page-git/src/tex2page/./tex2page
;;;       newer than compiled /home/haawda/.cache/guile/ccache/2.0-LE-8-2.0/home/haawda/paketierung/meine_Pakete/tex2page-git/src/tex2page/tex2page.go
;;; note: auto-compilation is enabled, set GUILE_AUTO_COMPILE=0
;;;       or pass the --no-auto-compile argument to disable.
;;; compiling /home/haawda/paketierung/meine_Pakete/tex2page-git/src/tex2page/./tex2page
;;; compiled /home/haawda/.cache/guile/ccache/2.0-LE-8-2.0/home/haawda/paketierung/meine_Pakete/tex2page-git/src/tex2page/tex2page.go
This is TeX2page, Version 20170116 (Guile 2.0.13 unix) Mon, Jan 16, 2017, 10:05 PM CET
(./index.tex (tex2page-doc-mac.tex (texrc.tex (tgtermes.tex)
(tex2page.tex) (tex2pagerc.tex)) (coloraug.tex) (eval4tex.tex)
(like-plt-logo.tex)
This is TeX2page, Version 20170116 (Guile 2.0.13 unix) Mon, Jan 16, 2017, 10:05 PM CET
(texample.tex (tex2page.tex) (tgtermes.tex)) [0]
Output written on texample.html (1 page).
Transcript written on texample.hlog.

This is TeX2page, Version 20170116 (Guile 2.0.13 unix) Mon, Jan 16, 2017, 10:05 PM CET
(mpexample.tex (tex2page.tex)) [0]
Output written on mpexample.html (1 page).
Transcript written on mpexample.hlog.
) [0] [1] [2] [3] [4] [5] [6] [7] [8]
(index-Z-G-1.png) (index-Z-G-2.png) (index-Z-G-3.png) (index-Z-G-4.png)
(ursa-major.tex (index-Z-G-5.png)) (index-Z-G-D-1.png) (index-Z-G-D-1.png)
[9]ice-9/psyntax.scm:1274:12: In procedure #<procedure 31a8a00 (test then else)>:
ice-9/psyntax.scm:1274:12: Syntax error:
unknown file:2:11: definition in expression context, where definitions are not allowed, in form (define princ display)
==> ERROR: A failure occurred in check().
    Aborting...

Process makepkg exited abnormally with code 2

**Comment by ds26gte** [comment]
Thanks! Fixed.

**Comment by stefanhusmann** [comment]
Thanks. I can confirm that it is fixed.
